baseURL = "/"
languageCode = "no-nb"
title = "Christian Engelsen"
theme = "mero"
disableKinds = ["taxonomyTerm"]

defaultContentLanguage = 'no'

[languages]
  [languages.no]
    contentDir = 'content/no'
    languageName = 'Norsk'
    weight = 1
    
    [languages.no.params.introduction]
      text = "Lidenskapelig bergenser med en interesse for teknologi, bevissthet og innovasjon."
  
  [language.en]
    contentDir = 'content/en'
    languageName = 'English'
    weight = 2
    
    [languages.en.params.introduction]
      text = "Passionate bergenser with an interest in technology, consciousness and innovation."

[module]
  [module.hugoVersion]
    extended = false
    min = '0.80.0'

[params]
  dateFormat = "2006-01-02" 
  author = "Christian Kårbø Engelsen"
  description = "Hjemmeside"
  mainImage = "images/profil.png"

[params.social]
  [[params.social.list]]
  class = "fab"
  icon = "fa-linkedin-in"
  url = "https://www.linkedin.com/in/christian-engelsen-7a07941aa/"

  [[params.social.list]]
  class = "fab"
  icon = "fa-github"
  url = "https://github.com/Cengelsen"

  [[params.social.list]]
  class = "far"
  icon = "fa-envelope"
  url = "mailto:ckengelsen97@gmail.com"

  [[params.social.list]]
  class = "fas"
  icon = "fa-rss"
  url = "https://cengelsen.no/index.xml"

[params.footer]
  message = "&copy; 2022 Christian Engelsen"
